global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'licensingservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['host.docker.internal:8180']
  - job_name: 'organizationservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['host.docker.internal:8081']